README.md
docs/filtering.md

A doc for ReadTheDocs to grab.
#2

something in docs and more readme

---

.travis.yml
rets/session.py
tests/test_local_settings.py

Dropping support for 2.6. Attempting code coverage now that build is passing
#16

Pythonic refactor

---

.travis.yml
rets/session.py
tests/test_local_settings.py

updating dev

---

rets/session.py
tests/test_local_settings.py
tests/test_session.py

https://github.com/refindlyllc/python-rets/issues/27

importing hashlib in session.py

---

.travis.yml
rets/session.py

Trying to get travis to post to slack

seeing if we can get secure slack notifications

---

rets/__init__.py

shipping 0.0.4

---

rets/session.py

Seeing if PR triggers quantified code
#43

options push

---

.travis.yml
rets/models/search/record.py
rets/models/search/results.py
rets/parsers/search/one_x.py
rets/session.py
tests/test_models.py
tests/test_session.py

Simplifying the record and results and caching metadata
#45

Result record rework

---

README.md
rets/models/__init__.py
rets/models/search/resultsset.py
rets/parsers/base.py
rets/parsers/get_metadata/object.py
rets/parsers/get_metadata/resource_class.py
rets/parsers/search/one_x.py
rets/session.py
tests/rets_responses/GetMetadata_objects.xml
tests/rets_responses/GetMetadata_table.xml
tests/rets_responses/Login_no_host.xml
tests/test_local_settings.py
tests/test_models.py
tests/test_session.py

MFR working now. It was the no-host capabilities.
#61

Large result set

---

.travis.yml
rets/__init__.py
rets/exceptions.py
rets/parsers/__init__.py
rets/parsers/base.py
rets/parsers/metadata.py
rets/session.py
tests/test_local_settings.py
tests/test_parsers.py
tests/test_session.py

default request method is post instead of get

Posts as default method

---

rets/__init__.py

uppping to 0.0.6

---

README.md
requirements.txt
rets/exceptions.py
rets/parsers/search.py
rets/results.py
rets/session.py
tests/test_session.py

Iterative parser

---

CHANGELOG.md
CHANGES.md
rets/__init__.py

created a changelog and promoting to 0.0.7

---

requirements.txt

Removing lxml, it was never used

not using lxml.

---

test_requirements.txt

not doing the pointless combine

---

rets/session.py

If the Login capability was used, give a better exception message
#86

Notloggedinreport

---

rets/session.py

Using the user agent auth to make hashes correctly
#95

Correct hashing for user agent auth.

---

.travis.yml

Looks like current code passes 3.6 support. Adding test to travis for continued support and testing.
#104

checking out 3.6 compatibility

---

rets/__init__.py

Upping version to 0.0.8 for next release

python3 exception

---

README.md

fixing repo rename

---

rets/__init__.py

pushing 0.0.9 because of the minor stuff

---

rets/parsers/search.py

Key val alignment

---

rets/__init__.py
rets/parsers/base.py

found a new reply code to catch

---

rets/parsers/login.py
rets/session.py
tests/rets_responses/Action.xml
tests/rets_responses/Login_with_Action.xml
tests/test_session.py

Action Capability is now called correctly
Also addressed issue where LoginParser attributes were shared across instances. This should just have affected the test suite
Fixes #119

Action capability

---

CHANGELOG.md
rets/__init__.py

version push

---

CHANGELOG.md
rets/__init__.py
rets/parsers/search.py

Pushing version 0.1 and generator handles no results
Closes #125

No results

---

rets/parsers/get_object.py

Image encoding

---

CHANGELOG.md
README.md
rets/__init__.py
rets/exceptions.py
rets/parsers/base.py
rets/parsers/get_object.py
rets/parsers/metadata.py
rets/session.py
rets/utils/search.py
tests/test_utils.py

Catching rets errors in multipart

---

CHANGELOG.md
rets/__init__.py
rets/parsers/login.py
rets/session.py

Checking the RETS response codes at login. Should make for better error handling

Analyze rets response at login

---

rets/utils/search.py
tests/test_utils.py

verifying that filter_dict is a dict type

---

CHANGELOG.md
requirements.txt
rets/__init__.py
tests/test_session.py

Version bump 0.3.5

---

README.md
rets/parsers/metadata.py
tests/rets_responses/STANDARD-XML/GetMetadata_lookup.xml

Fixed readme formatting, fixed and documented METADATA-LOOKUP_TYPE

---

CHANGELOG.md
rets/__init__.py

closes #161

---

CHANGELOG.md
rets/__init__.py
rets/parsers/search.py

Trying to fix a unicode issue

---

README.md
test_requirements.txt
tests/test_session.py

Finishing what doppins started at #171

updating responses version and headers parameter

---

CHANGELOG.md
MANIFEST.in
requirements.txt
rets/__init__.py
rets/parsers/base.py
rets/parsers/get_object.py
rets/parsers/login.py
rets/parsers/metadata.py
rets/parsers/search.py
rets/session.py
rets/utils/get_object.py
rets/utils/search.py
test_requirements.txt
tests/test_session.py
tests/test_utils.py
tox.ini

Using six to make it more py2/3 compatible

cleanup and full py3 compatibility

---

README.md

Adding some readme text example on downloading images

Py3 multipart

---

CHANGELOG.md
README.md
rets/__init__.py
rets/session.py
tests/test_session.py

Parameter rename cookie

---

rets/parsers/base.py

Looking at RETS-STATUS when returned

---

CHANGELOG.md
rets/__init__.py
setup.py

0.4.7 released with support for RETS-STATUS responses.

0.4.7 release

---

CHANGELOG.md
README.md
rets/__init__.py

Styling markdown, forgot to set version in package

version bump and styled markdown

---

CHANGELOG.md
rets/__init__.py
rets/session.py

Attempt digest auth initially, and fallback to basic if the login request returns a 401.

Basic auth fallback

---

rets/__init__.py
rets/parsers/get_object.py
rets/parsers/metadata.py
rets/session.py
rets/utils/get_object.py
tests/custom_parser_example.py
tests/test_session.py
tests/test_utils.py

Trying to be consistent and have all requests return generators

more generators

---

requirements.txt

Updating requirements to make sure we're still groovy

requirements update
